export const GAME_CONSTANTS = {
  PLAYER_HEIGHT: 1.72,
  DEFAULT_FOV: 75,
  PLAYER_SPEED: 8.8,
  PLAYER_SPRINT: 13.2,
  PLAYER_GRAVITY: -24,
  JUMP_FORCE: 8.8,
  WORLD_LIMIT: 95,
  REMOTE_SYNC_INTERVAL: 1 / 12,
  REMOTE_LERP_SPEED: 12,
  REMOTE_STALE_TIMEOUT_MS: 15000,
  DYNAMIC_RESOLUTION: {
    mobileMinRatio: 0.65,
    desktopMinRatio: 0.85
  }
};
