export const RUNTIME_TUNING = Object.freeze({
  CHAT_LOG_MAX_ENTRIES: 36,
  CHAT_ECHO_DEDUP_MS: 6000,
  CHAT_OPEN_KEY: "KeyT",
  CLOUD_MIN_AREA: 800,
  HUD_FPS_SAMPLE_SECONDS: 0.5,
  HUD_REFRESH_INTERVAL_SECONDS: 0.15,
  PLAYER_COLLISION_RADIUS: 0.45,
  CHALK_MAX_MARKS: 2800,
  CHALK_MIN_STAMP_DISTANCE: 0.17,
  CHALK_MARK_SIZE_MIN: 0.14,
  CHALK_MARK_SIZE_MAX: 0.22,
  CHALK_MARK_HEIGHT: 0.032,
  CHALK_MARK_OPACITY: 0.82
});
